apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  name: logs
  namespace: kafka
  labels:
    strimzi.io/cluster: homelab-kafka
spec:
  partitions: 3
  replicas: 1
  config:
    retention.ms: 259200000
    retention.bytes: 536870912
