apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: action
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/chammanganti/homelab
    targetRevision: HEAD
    path: kubernetes/resources/homelab-action
  destination:
    server: https://kubernetes.default.svc
    namespace: homelab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
