---
- name: add gpg key
  get_url:
    url: https://pkg.cloudflare.com/cloudflare-public-v2.gpg
    dest: /usr/share/keyrings/cloudflare-public-v2.gpg

- name: add repository
  apt_repository:
    filename: cloudflared.list
    repo: deb [signed-by=/usr/share/keyrings/cloudflare-public-v2.gpg] https://pkg.cloudflare.com/cloudflared any main
    state: present
    update_cache: yes

- name: install cloudflared
  apt:
    name: cloudflared
    state: present
    update_cache: yes
