apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hld-tls
  namespace: homelab-demo
spec:
  secretName: hlbe-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "hld.chammanganti.dev"
