---
- name: update ubuntu
  apt:
    update_cache: yes
    upgrade: yes

- name: disable swap
  command: swapoff -a
  when: ansible_facts['swaptotal_mb'] > 0

- name: disable swap (fstab)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*\s+swap\s+.*)$'
    replace: '#\1'

- name: enable cgroup memory
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: true
    regexp: '^((?!.*cgroup_enable=memory).*)$'
    line: '\1 cgroup_enable=memory'
  notify: reboot

- name: enable cgroup memory=1
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: true
    regexp: '^((?!.*cgroup_memory=1).*)$'
    line: '\1 cgroup_memory=1'
  notify: reboot
