apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stats
  template:
    metadata:
      labels:
        app: stats
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: stats
          image: ghcr.io/chammanganti/homelab-stats:latest
          ports:
            - containerPort: 8080
          env:
            - name: CORS_ORIGIN
              value: https://chammanganti.dev
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
