---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: homelab
spec:
  encryptedData:
    .dockerconfigjson: AgCHFm1f3Wdp67rCYWf0i/T/1PIIEHkIufuSVZatZBVfkKlHlmw7joOAizZfsebsHiEF/c/mvY9GOLXkdlfpOgZcri42hpNIQ97rv2/aVdPHPCR/qa8+ETuHGMZwH9vnX/hyWLdunuEr3LdI8POGZkMYSh138j8/auQNS1z2jrmqn27a7GmfsacpCTNSQUg/Z3MaoPgU/44VmRJ0Q0k7duBiMG+3EE1Q519KF+La6DPT51E8UzWhSF9VMx/6EmnEV84sY69o300AaXOGHBLf5OR5jnAwI/bz2Mt7NosKHi/8mDsmS/53wGweNMzQ7qmmMtx0dZ1LAfSHK6PC3PiCBd6UxS19WiIqIO9lbqHA3PlLOD/OJwV/uq+m8tFLwpOE6NXURJOMe+podDTcL9ROxEJhaaZJggWVzZ13yULfHMbETaulZnkzYf+OH9gRlOBqKfLygc77EUv0ExHGhRrPFQ/K8fQ/dbzU9rsBHB4DT2otCz3I1eqNyY4jnZFIV2vcxTME9KL36XR8zugG3iBvGty2NDvHvLBOeu8Bq28or5tqwr5sfW25jun7rWEK40dgqc8/cuXKMhGtP0mC8/ShecksgU+YdY5u3Bv5TbVTR8ega0qJ9yf4wg0uFDE7xf8fyg7fBJwZxcGu41XIF2BI/I6575pwC/DSmsIFdXPtHrh/g7KKMiSFGmDoGJOkfUrCvTByIU0P6w1VGkLqrAvmvaS/HzP7bBRoM4gtXH4ONoT7fejS6DPh6C8D+NHAYTnwFFEfkF2BAIMEQavK/lbqRKVdNaTfRjM0WWYTA5LbtdbGqAIWjcsjlPooGTCAGB5rnLXlSLGPLJNvBtK/Wy+Qtpq5FvITPMqCGsu0oHVxUCONsFf7LA6qa4JAluuk3/5nhZSJMBoF++swk/MdmQVzP7dHG7u94Ti0vFzrX431JsOiuYv5gOd5/ccmnA==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: homelab
    type: kubernetes.io/dockerconfigjson
