---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: homelab
spec:
  encryptedData:
    .dockerconfigjson: AgAmAJzMoiW1/GoUejfEq+EsSEA1kEI+oK+44kPjlHuexHaAbXytO16djayMm7IqvxlSxos/lq/4gCOqipK8jjCqOXnctD5+4eKch8AWp57PsHYJYt38wI4Hk7dRMIL53fHJzpYxCdkb5j4MPVrC3DWyBAoudOMHDO57NV3saK6aHDfSV5QvbqsCDuOtDZxDKS2a4rY9rdJqFl0lrSY0gaTxIybOwBifpIZw/wcB/T6kSDCSbuT7+qvJW/GLVRcu/6jZsdpW0AHwGbdWiEw/ZYPla3Yq+knkHMnkzlLDX3o0G/wcXkP6i6Qamc7/E0Mlo0nTSCi1GrRRH/YdNMxJd2lX6pcUcv805AZQ+xobrDfJ2n7sGTDaAkBNawoIhbz5UOrErxZYxFrMLJ6TQojaXb2zjG5EOZ+THn4gPTDvPsmP7inDoBrhzV5hjxcCKjPRK2FA4TkRCXVz7W/q14yltyNo52gGk82QFelDgqai2a/d6H+pHVLfQEqIEpp8xA9ztdbVZT8RfEDMPhGIJyP89+S8xwqWxc/fRHRaX4YY75Ah+9WTHlmrpuzQ2kCPCf9xHcPsvXTWA8EkeKGxJNhVcbbSoCy+ZRDD8XcrK5tjk9tx0wViD64vmBgmETRUA3oCDJrk4YCMUYK94roYAamiw7Dxj2LUZ4IegqlOzsI/OCKSdetBd1swaebCrzFqOLYZkLH/MQNchariJ4+wzPgoWGMfGhJh/YmBetis38CX8W9THnFQfC+d4DK+Jtdx9Z5K/x2d9VqZKThuIVlvrWt0AQSlhAs9v5h8dMjKNEgpOHbDvaY2L/DSyHfFTjYsGiAWHzA8HtuOwjMLCizo/OGIps5w0GyHXBlMFocTOdFc+cngHbUs0R7VJB09eVqtg9KkRaUp8MkFJuoHNbj3UEBNhuvlwJpFuyi8UDLxX76pR0deyc5XEXc0fVNNBA==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: homelab
    type: kubernetes.io/dockerconfigjson
