---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: homelab
spec:
  encryptedData:
    .dockerconfigjson: AgCgNgsbI+FGWI6pT4+Lqs9UJtbCuEMNKSFccaOyhNoGg7C4M47FsLD4eEedYfxFVCmYGKPH0r6TcG4ZRQ5uQ2UK6AidCjKYl2qz6hcVaPLZ3ERPYo54IudGuBYiNWFUV5I7SmVqqDvzcZNmPLgUa3al+v2CO8fkYrr7iwVsf2OQ+6LrWSjNW72hXZYK2/+b4BPeWDw+akP+DIHZKVq3eayuduhgdkA6KgYuXEqLyUBPRvc9YD9Q6wMJ0JPVWtQXqZaJLzKomS8e2/EN3P2L4hzpRS/dNTdQAdfOfoyUkv3N3GUhO73evGvBkIvPE40kvrLHwPY7FQZj3rhesCxI56espNDE0KzBBZ7y5X8eaywSydcmY7akcSMxISI3PyGfp8DujDzZdyFxVvhyN8F9vwXBI7ZLFp7C+QzkSa9/SpRkeECcNRIKztHAyB5ajZ3UoRYF3R9DWTwnZ+urF8fL5htq+aUCKGOKkRmaDCo4prxK5sGZndYy3qrxWnAbbfcI58fEhMY8ZauX0eOwIN6f7ek5l7NrHq3E6JKDfJ45cdgLv9iBSqkxTgeZ5g1qBq49K0Su+GJIqRsLYk+DBFeUqm/HzG9GZylf+uM29dc/RGg86iaX4p+nsGB/WTZ1Pfqi/H0zfFp7bVD6gKa6psJ+5xKa4WPp1otE35Y70FcuSN9OV+Gf51aEdT74wJmMGnaKZC8JdHkPwTEUIEtP4dJ3xYNGWbimOvbmULgaDPtQPFNijlAcYAtZxJ9Gp2GAaB6ZrJ3MpAJwZ7++YogHktMnLpf3lHRnmgUIXTukdtKGjpNuDJst6iWdDiIcxhgl0TbVM5DzLRVlsFXh/PZGq6HR6F5cxEPMyV0X/xy/N5v3p8iL1T18kpj6Wr6utCsu4j+S03eeq+V4rHPHP7NXcWS5rehm9fxKRdJY825yJTTEjAjslBu6wkx+mOVg5w==
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: homelab
    type: kubernetes.io/dockerconfigjson
