---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentry-panic
  namespace: homelab
spec:
  encryptedData:
    magic_text: AgBRWu9/wN0DWYptC919vcjQwKbuYAEk61Xc7gEPOtxOKxES1q+ojp4RzzhRZpvusuej0OVNG3SiajDalv3LQHf5bcUkx+3XWaouowFROZ940WEFyieN3N9EjCBn6F+qYG1fMgcrH4g8mDG6QARwPpYPnRpo9SXLpgK3/VmRNjq1Fegixs9SHMuw5xcUNGAApkhrL3dEeO7ifL+LR6IxEH3TnXlQmahQySq8BO1e7mEPETDLfsKF6GMspoaAGPadXjaRQiYUVNsTF051QO3SaTmOsUw5Zk0mPu/zxkb9nqE1+7I2qQdGRWkqyvZ7wxJgTjaBaSJjbvsUAimVTzUsnxrrzRKCOuy1I129hhbzi0BltR/U/OJGK/KHU0kzICOmabohF85PqGCyLwvbKJ/EDzPZEVVGf+SsxX0f8iHIH6Wl8FLv/OHRb9VyYF5o0q4AiG5qknQ3z1c954fhObkJwfzQy8tk2LQhvbg8JKFAXdogdQZ9FDCZrWLo71rn6zUzrZLqqwPmZPAgt6n6bZ5NRAQrbsnnnzqbXGf+GvGQtd2SChUdeFZiWnDRx7oT620jDWsVwyTZEOr567r8CKXVhimRs+RSdo+32rJfXPoSgb/XX1ZzKD8qLIJgU/Q3ilV7UEeyz5yFMqH2kI5bP0wrvnGyaIOkqfJcL4sVUhNWlwmcffYJvBTlnibGtWv1W7Qi2kuqcHpKidqLrl4WHEaC9Tebu5TC116I
  template:
    metadata:
      name: sentry-panic
      namespace: homelab
