---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentry-panic
  namespace: homelab
spec:
  encryptedData:
    magic_text: AgBmY9zqRi5z7Km8560F4a/pRyNIsfTiuzFOXQ9xYBbp6Ghz02QSniKWCkZ+tWVT+KiKk8IXwP65oIlwSzZ4BRKFKlYJ4kPY9LZAHo7j1E3Ujn5dYG8MAnJJkjuIkKhWniCDgOH/g6v/pSHAaesTMUJqUVMm7bDykxFUh595F30UCq3NUwX8FvAPmh5AnbJFjqn5FPo/y00kR7u3I7U1Fw9Ke03ZUgITyUTauyCeFqHGji40nvSjfdlBQ7Cv9J44wiZSw5U1FCYhZo8Rm8elh8UgfO1xfx2vKjc7ZUvqO61v40p4ElMA8OjJIIXPpaYPE+T4FXlMjVy0gYhA6R/WNva0nsWbRmDYb6lCPwSurdrPFWxaHvDZZLCkELT0r95OTL0xwoUcu0/PxxM8wBWD/Ht3mu6y2pRI5i8U1T8YFUqUeQV38eD/6HD95IAy86SHYu1tFmsWqDpL19ForhDGeBlsI2aH4LiWFM/RUmA7SGBexbKUBzQQP40cazgm76iI4YieFhZpDvTxtHcpqAexA7CqwWZRWPbKfRGafZrjcEnwL2vbjuAYLQf7Rkd6xAl3hSHUwkoBVAsBUcOF6R7/FvlrdhcDWSCapRTFYvimQvs69TW99+felC+IGm4nZVlvR4MsE04UVjHDbp1H/NH4ShGI9tYETKZcVivzwN0CB2lIQeyvVqqZtWY+EmaWrR2uugrfpxbsOmbKb+aVYaCkq6uVm73rDJiS
  template:
    metadata:
      name: sentry-panic
      namespace: homelab
