---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentry-dsn
  namespace: homelab
spec:
  encryptedData:
    dsn: AgArHFpp5JsWt7lF7wXsRdKD1lzescgGegPmfWAX+f4uP6c2PyRurQoyHKMxLdKwClndoBqc2SH5gYc2HD9j1A1S8S+JdjGGQQUqkqUo+hFyXION+6a6pL8eeZVFUZFa34S8b7QUtSCoHXdhkohgkz6hI+UYGMcV/qCoB04Q1RGs/LLw+E3Z7BJgcs/Ig//bWdzY/efAngf+F2Ru5uKn+tvcudja+zxjjyqXYlDoYXeKEsuNCYBNGT2r5gCdp9JjDbzzkbkNjNyJGPJfAi6TXB8e9/WNlrJ+T8Mnlk5ZzCqWK8q8Ie/4D0PddAi+8GW1c73hxy8QTRNiSOt0DEzt6w48S2eckGH+/Dfl5+hAhC3MgHAHRxB5kMbpCUeX5ulTYesZZ1+lNNME2aJSRgohZp5FC94DekwwkI/3Rl8GxgopCvijRc2XEdp3qERpGs3PyTcnggxEUWdsU1oF0OFxN+c64tB28etLd0FG8B0XGZzQmb8xFoHopMpEsKU/fNuhZvXVzv2RCYfIc55frTq4+HzJiEVXxs04okcUL5xol4+sd6eGnn11OHv8EPSIhl0Dp6sR6gHRPSopovuVNx/UB/IJXT+eLffPSVPGl1z8MtDQwf4tPEZ6H6ww052Sy+2/VGZSLhR52jWediKhtmghZLKVLug2lGyGyYD8sOn459wRkIONsXxAvjFYVtmIAPh5Xm6jv2L/YQ6+YXGIxt3m6U90Rpn3u/4OaY9EaVQpekwZZrUCq12QKCIJVrWc3TUih7abjMMQ7mXFswplc2yrCtIEtx/yc7tCoeT1xl4mjj0rRHvZFezBupWkgQuasaqTDA==
  template:
    metadata:
      name: sentry-dsn
      namespace: homelab
