---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentry-panic
  namespace: homelab
spec:
  encryptedData:
    magic_text: AgCBsulywhOEdx3Ral7YgXfknC0vcY3W7CSRkm3kBrqdujDuJuMhhrEFl36NWwf/dvr+azs2YGkyZm3Bu+0ZPFOWZAq7UyUUceAvONX9E1qeKPdRX1/vHrU+tsQkR+lKfS0GLzviHqaU5AJrgrgP2qNN7ZmiZC18psm2wuCfbB4OugbE1h/+9fPbZ0pp8utIGJHBirvLSLZC7SGJxDozjIdeMETAh2sgRY+uHpFOD03hf6ysVegsUS0ki8WkdhQK5IKOwLiQIuD9IZjaO8EaCxU6iASXjDmxnf5tlQqmYxEl47JnI/8GG6+dlYYhcQCjnclqTRYUj0uaq+GNt2a6P2f/e4eFxR6PJqx2D/BB1v/FvPr/EN2XxV6by/6K71/gHIgnU7uLhjxz3VTRXFdolZcKHaUUgi+lnWf80Sq55l0J2X006Ugp4TbBjuSAd+PVAI55sPiwGuxGK9hzQg4slqyC6s0U94hnhHSCHf+NMqOZeVhHZai6fJS+apsI5oViQwAIPSvA4dO0cRpR9ZVKBZQrrlPVuHxGw6/2aY83ixSO+4Ch4khY7eZ5LdRYVr2QnudauI4CX3c5e9XtCCzL6koLWLu91qziGlDFTralYf3bz40a3KVJfytn9lwKzKXdliAE6Tnd0JE/o8Em6FGC9ITc/nh05/JcsIyoVaqyQzkVE4pP/Z4ZcwwlIAgPozA5E+EpyP1ST+hYci1eAROxYYGw+fqcEeBa
  template:
    metadata:
      name: sentry-panic
      namespace: homelab
