---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentry-dsn
  namespace: homelab
spec:
  encryptedData:
    dsn: AgAWjbrUwFaE3wq4yQFwa0u5jn+LfIhnpsE9RYCP8DyOVIRizAPIpMDYY0XSRowxzGW49gdVo2i8+hACKTDDp6/OnjsYgJlhZPo8RrCExAv0NaawxvmjGjQN1QgzpEiMUypLym835lncWNAKHFpk/mCgtGko13kG4hRW0BMU3bobWOF45BMMh501umfAAZpGop+Sdty7Qy7jvxS1lzXSwfkFFEP+JPqgnN808Ec9TXkDgc6mw0aCG4CG3MA10Buv00OsC42xfrzn+tGUS77tkpxXRUFsbX3ukYvJGAC/lAjgj4FMn7QSJ8nR5gvA1rMgrgSToOsoyfTH73r2tr6+IC0m9WjoHlaDg7IYhA2ANU+Bml7OT2PjxD3C+oO98loh/gZN4+PZ1BSserZBSpR2SY57uBNEiN/2QEx95Z05WiKN1DmwIObiDhuNqhf+IS1CK+uox8ew/8fE0QG3ZZQmiXZNzYQXm1MW1wS4Att1QDRr/zBsZclPwdmqV8uN80GwKim+R8y5uB03fk9A2nCPPC7ZK6hd/My9VOqLO/ao5wMKaec2YU2DdmVfl2HyRmfiDFkaX3TpEqAFxcnqPoX8LlRzlqxwJgntwvax6jO+50gzZzv683otOvuhtn+Lr9pDwa7otEnwu8KXV/m/Ax/1wwR9zIE1Dokl9XS++17+y4rLvZg0/xPjZDOwcL9SuwGKOWWaQJ4Gvu7TDyUfnVyOvkL8ONW8PGC9SKpcEWje7lAJyrSZg/xlc1NBSUBc0t+fsb+rnAdJS4mV/moHnfR7aS+4/AqrnkzKeQhE19gLgIg+dzwclQdalxVxYBQzFhL3ow==
  template:
    metadata:
      name: sentry-dsn
      namespace: homelab
