---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sentry-dsn
  namespace: homelab
spec:
  encryptedData:
    dsn: AgAJu0Lr2JLFn4RUAwIwYUTYOoLv3TIkuLuB5DN5TifR1Eu2kidsuVG/dTh6aZMQZKSCEziu6quEQxs4AG8K+EmDJvx501bra/Z+OQ0fh9rL5PD/6hQBidRr6b9wWpE36f9GByCc9uqhK4NGBJ4wFtkNR6zzf44scFwLAp3pLPgl+Dk0GKP9Jl9b/T1t32AWKwbx8imQVcqq0E6RatUNo9vib76WJjmCA4jCQEmOzKdPeeg92u/6MUALvxdw6y0XOGFNMS09QLZ5LzgxUN5wYI20GfrlkqcJA2Uf5AWhGG+UliHWMKrSfeyuiIl1XG1maCOWFh5Llj7xlx2HWKcebPUie4GDwCfrL9/rhD/fOtrGs7v+U8gH8wH7pw7FoxIoaD006fBYwkzVgXudJsxj24kJUIKPy+jheP9DtYAproCMVr9+0F8pJlaPTottaYWwFUkbnHTDd74XTfDscCwCkM0W+nwvDvVVBB+UUGQ+YoZ/2h+kqWnpxzZy4n2ID0uE37ghaHSZ1RG/ikmBOb1VvTMJJhLX8uVpjGoFYDhV8H4035EzhdwAQxoapNh9hDbxaG3vPPNp6qTFKAemTGOSCTt/DjlCjJTO2UY9q5FePpXHK+YnzcKBDxkVRL+ax/orvx0s4CDs3NHd+uPlSmu6HcJJl9ltxQcNabpGRVaN65nYPtgykvRVzOm7MjiJ8aT6YIrQDzDMNZIL57unhdZDWYqM8fZ9yCPBqNcHi3zuN8OiWEyddaTHUH7OcYhVJ8bI/eiFMJCPlY5P+uVUbiLM03NkT3lCIcurxPoQzjm7lDu9SotMqe8UaMvEp4nNkc49dQ==
  template:
    metadata:
      name: sentry-dsn
      namespace: homelab
