---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBUsL8uzfkRbQLY1K6Mo6vHUauJPSsYR/t9lVwBcgOVTGI0xL/dHibeg7aBK3cYbWlrDoF8hnGGBdD2HrIkRhxVh0mDbfoXli8bmT1f+5UKx1iCJh0PQ86e87vM9RQJKi0KVcScacLCHBXuEFwfmPEXVET6zu+bATLgpUgxSOhoxi70l5q08+rrCXME/nNCTF554Ez+HSIBsJpY4VFbVe1QVLlQtLvobFS5UjZwqeGwXIUlnJdNDzo+mK1zfyw2LeHdzlZwKPIrHLpgL+y+881TPfgI2u9wgOxYRT60BLA/wZULz3LUO1MRyHSIkNz9ZrzDju1NO/V7CJU2reJAZ1e3nUr79IANp0eiFlFrysX5QuXALJT/PRbbdAzc7I5ab7DMHi2z5Ss/pxlwNens4Zpe3E9g6U8++4eOpYZYpXaHP7rnyGdMybLKDFUFefj6WUk/MooLYrYPmqG407OS8y/+yri9C65JWNyLQUeVgN6ncFz+TJ5ACCzIf2Di1/SZuqDsomGG28aVY6FdWJEPbXX6X7Ylam4D7aAFiYIjfXYmsUG25rkBXtLKxyhU9vbRmZ1FYEjZ5kmlRLfrUgjPI0dTA6PKAe4COtN9RyPcWLpUYcweyzRQNic6ukBy+s5AFIXNVH5yJnU8qHjJ2xh3WHVtF9S2odWFykgVLnrDIeZIl/o2fcHKWYaL/XPxMCqlsFfjZuONr8KdWVu/cdHTJIS5EOIuxd07
    admin-user: AgBMlcyPYkZyPo9dt5uD0mNh69QaILjTvW1S+VyMj2wgrd504r+GZhgmNU2Uo89zYMWecLfE8o19cCgeOL0uR1UMfFHsqvtiw9Sb0pmP9YSkurlyUjpkW5/LzMcM4ZoRT2I55qTbSa+5fFhom2+NCiF0Nnha5qtvrSdVLzvTaFA9sqqhYQKbpVXsUc+lsr9sZs/Eo59Qduax3JzArxn8d0Cg/X92Fl9wMrSdxQ92pq8AY7g24nyVXxDb5QfPfEjOcC9U2/Jd8h4eKlPflvqi6lNcqTO44W2sSlf/+T614OpzuePYNr4PuE/l6R6AYr9iiJdNM6hyNTTgm1ddqUx1jDl6R4YtNMTgwwIinCRpvlgjEa+OzUZh+Vyk9UBkx8RGm/vN7Us7iYp+lODLda5wODiuz94JBCbDHDs/vOKhHn4wo8mCY9fd0lUSsB7n/jQtF1LrxThuXFvbde5+IJ5ofI4mBxOay4hjLcGnCngo2pMVP7fks8R0x8ByLOcwbwl57HjVvf0OhptnyckWG5d+K3fhQl+YWfSZz77DmgD+FkWAMsgZgIYOj2G2f3u9SexjXgPGbGL4cWai4RKjqc6wttouEofq3VftKSi4CrPphTI4jKKz1d9vXtH9V9znliwsw724EsduHdajCW+NyRsG6TBY0hHZXbzuf0Pl17ONX/A10NU9zsRGNNePDlz04nyLIS6ZpTeuaQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
