---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAwmXFL0RIgT8oJn3kmar0w/5Jq79TNkO5si/9I7KKuZ0n2YCtFURihMV58r3NXT0ih76ifZjv9y4a+cf3NRK0rArjp/AnvGuoMeQPAB2xdS0ldetygzoCylIqnoGrzuDH02RSClxWRhBi9U4HWINDSZlg94bzgy3ETLwpFj8sXRp7QFhQ7LiOUc1qSZPsGIZ9nXLAB/aYbyw4IloCjjkVw5D2d+raAbdhMhkgq2PSprIbY2zoh0AJ/2cwapg9pU03efvk1dHaUflXDBWXvMWCDmGytHTLUI8aaknTN3KHG53gdh7763W7JObX95hyoc/44QLb61Sie2SKv+PCCIwU92MV1C+guCmyNcCcmAHbT0rNrtw5Lk3vKHNIlJiglv0sm0ZYga82S5nHZxReNBSj9v4ONz3lDyW5IMfuY1GnRUVV5mzv3tue6VxKvPtWbIVRsAaAY9PzEBbd4JD0Ofy06WzSiWhO5yOdDOHm2VN3V0GxpCDftgfSwA3fPflxrJX6BEp6Oa/yCfWaBj55pypY3Pd9PtdWzfsXFRnWkkHz8Zy2Z0haXXzsfmZM+w+Aqajmqd+NnKh6BVqkvPzRmB6/ZgnK1SKeoOcA5r2OUWS2FL3GY45uJRj3PsYRqeEJy+fK6QXif4UqsuyjZ9RcH1Om0O5aN5mSOYdtObS48zaxclsBNpyeEV4zRBh1FciJCsOiwqIA3QUpEIqjBUlSBKNrK4EaFeRZX
    admin-user: AgBh8wAvuA9+9ApJhe6B3hsUdxOPJC1logxMrdE9j+pNk7NAd/YwQit4b9LsL3GJO1/eqf+KABCugOt7zeSr1oCNHW22lTtAUkes5nLVAJvHXuNEdL1euY8X05d2ui51CWNdJhcagYy+aLxxkgBKUvbhhzdye2hWfXWw9i9tl5+tOkB2gaDTMIcQCnK8uJwxc+iQrTuNwOQ01APqoyclIjd+gd4qLWV0AWhP7ld5zmsN8ed7r46/bWMJmDI6ccJ5k617wZwSkDwB7+WyZPF+jov5wOVm2Wy+DONZyL72RIZ5HnvfQ98dub65ZEhXgWnmonQ+Cg9j6PKSGZy0BcK/FPbQML2TJGupwUV0cBkr5UXI1x5LzTecG2t9LhGzq5f1Fzf7fFK5N8PR+hlrLkms43dsr19s7q0Tkm5EjmV+sMimwGmaCE8tVGY6cKjDd2WdGKXJusijNRZsTOgheYsX1B/l3KeDU10Iy1uLFD3k9wrv5dfFlWP93NyqLgmUByxN2W1vSN6WiKTPbchckxFnDhvxRnfRJ7mLgIA/SNC9NpKgzj/CbwAH9KwUr4v6+HnaOgOgIpRpTL2PbXZirg65gHV1gn64fPOU+Jh3H1s05i6kcUoN7UVzMckdeVohFs/T58eLjXgODRnDk+xM8Gy82Sred4NlJu+jY4tc/YOGtwDXWcCMIF0fVhMYg5cszIwfeLWb6oizDQ==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
