---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin-credentials
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCz2onZBEi9yyqlVUdbTc1SHkRzX4gN3DrHF4Rr2F9MIhsNEnSNOXX2WQqtrX0PuydcvhLrWBC/Z/EdL/OKbKEpEu0VsR0Qv9McFQgLcVYUpuBvVaE2otN526lcGo4WpXefD4LawoG3Lt1nA2DZJWPlQbMiDOM3it256UtSYyyErtSrwNk6hK2laMzP88qUpm/nn7EfC0Knh/mdnaynVFaoQD9+Ts87Vsya1n6dT1LZ5v/YmM56xHcWbRgSYFj91ililpTi/HAKvWzOSBvNZxtN5/lDsqZGjCqHaezvmc/OrvgybPsHHBpymDOzdvG3JzxJ3eu/p8c6VlTkN5Gu32kTP4dVky1fwC56BxR+pi2Ghyg5XQXSqku/bOYKKQW2iYZtgKoQB38Rk7DxYza8DfhmUiwRyXnaJMyFwus8UbTfVsK3k3K0exJupJa8q6mbdIJNYNHsQ+c8VNEus/igGoCj1a2oeKovQ8WoEGoLi96nzQAwRANqHR+HbunrfUlm8vbQnDCDYdcnIFKFaoH2Z/EFyYyBs1XihYB3mRjZxGblbZXRdcaDs1jHDTFzD1SuIaJS1pVGkMMtxocuA6KWlGSUEyaYFE0XKhSr8a8VLGcqHaYvsePPROMefSQwSnQqPn1uQ1CWSOP+y6H+bE4NsTvwne/NQxGJwPs3IM/h2bsFyUIQigw9RwTuRc9Q5G909pC7Ek+vv5zZMGIFC4LmLgyacFXHZjvS
    admin-user: AgASpEbl9sVFeYgd0GnJRDS6TbPYlPfgGk9ZZUzcLS25LkSlyLiOVbvpXp5xftxs1A+PTuku2/sLnkesnG8pCHXSNkd6I47TY5zJ1AHZUq7GxsINzqihLZo43HAXL7g6GSJ8X0dHrTtELApyR6jBbgn8rP+8IB/hAOoefTphufBZs3pf40XWHKtUAC8yPuhdAexYJ44AN3o8oyJU7w4uEw2QDYFqQB2q39VZj6K+GDAiM7lfj9SWBQr5X40AEdBMZeT16JypwpXksPpCmGJr0o0uNeaP/s3ct63uQVZV2wvDSqqxjhs0DZsbYszDT+XUjtGIbDn1Cf6J6WITHi5hTTjUI5slH/YBLsnqFk2S6Bf30cp7e2loFVb8Ux1lBSb2LoXg9MOBIbNiEyaK6MSjVUsZxR2HmqOKHiAn2JMiw1lCaypkYcFHGhi61ihByc7x5Lk3FHhWaMCCJCHA2DuIx/5uez5rklVeC54OxT9N/POWSq/gjB7kdIf/ZCJNW82Q+VoeWpp73aIkuP6piVnyvAOvLkR9zsez4shdoV9Zi6YmFMsLNd4F7SII5KZicQnT5CmW6uvsoUtPTDkF7epCmyqMWyg9jXEJHtzE0tIxu6x+KcH6joMm/ENSfkwxT8/1Mi18BGnN6nWnU+Egw87TUyJSRKxcwlKMc8GdQZ90Az4YXlnAw/ho2CeQHDIjxThBvssNWqCXIg==
  template:
    metadata:
      name: grafana-admin-credentials
      namespace: monitoring
