---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBtp+NfldAs+XrXqG4slMEN0AH/w0febiHeJGAKDK1HsoANO3Fh0cVYZ4NdcGWADv2r8OZ3oCfP9pVwG2jazHPtocmGRdpGEBOYdQqsEWXZnWmnZV94X+Sa+z9e3xRoc3MNrvFh2dIW/sbmMv2BT0FLkmAsJtoc+QFou6Sb09LRz7SDt+pXlTxUBVmdUqdGAJG20Tq2DoXq3q5jDp7OxXW+9lxTdbMa66bq3fp2tQKR6tMyP7Ir/lZBUH1m5oLf1SeGtZPQ9AIfltN/PNFMqCrXmjcAAfdS26bDWCo9EfFk9de0WNmyzqVfykMWE4+n/lPfemqcHLnXMnYsQuzwjC93aMOSzk1gbS5RFnksY5Jr251J/PIc8UGozZZrHM9W2sq2lOxq9bdeID/fNMqn/85jnF1ryn35VV2JHyaVEPmlkVeNw0dxNW17Okzu5OqUNGdm2QSwh7kVdGRZtgJLB5XZDtWnOO5vPbUigQLYVQ5olOviq8Mv3dTtLs4dDE5rsu+k7X0aqZ2Q+SuqQcxOyX3yxeOF7nKxhg0jr6IqcBE4fMoVmONw+vGDiP0YRq6ImrrijpxFHHR0mndKPOnFbdLJQT352Jcz8wlqlp0inrQ6bX8b5v4d1pzSZ+gMan3mV4WpdAatjY6y1V3/FikPAGuBJxoTVvUOAQUs6HVpRQu5/bYfJISAwB/vnOMtOKJ4KW/sbKnxZsSP7DEyuOwL93ri/igi1RUUSpw+H0gGFcBaqHlwOvMthnQPv9fh9cskXTPB0e2X9g==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
