---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgAdlYqTuZ+ZM1rFO8dl8YI2RHRQwOBqRrp+QkI9U3kZePdKtFTwQCBcI1eAR2hMmZ/Ir4ZOE3kkDOHu/QkanoeL38AQXRD31tJZuhC8xCNeYqd/ZGo5SGMb8bODsnRhQJQNjgkOgkRcCEn9atSAgcpaLF7qx+gIXpUwIqthGPJpjkr7S6d0ukFKfMsZ/KQpYzdqWERaY+IGl8s4dIb7tNOQvJNrui3FSDmmHe7YT4ZA4RjZiynrmYmdDRfFWtj6OOQ1m0s5jNk3wzcj8DFO6488rCYsGjoqPx3xi5/QfEXWhnaJGJxN0GoQBKNxA240thxRu7NxB+T1z5y7a2TKCdtfbp2FjCK4ND/NZATFo+MXs+OkukPIpCq74noWU2y+hro3C5Y5t6piiGJvV6dVoM8K95Pekju1kIz+EysVhFNaP25k+RWvVVM3FOh55Mv4njsIxiTRUUVGiKJPcSW8Bw6NWzPsXBcyq5M2avBbo2znPwG+eF0uD2idJDAe4ln9hXgAVfs+zp9GmPbKk9OM+dYCqvO9sbtMxVyjNaShWO07e+/7vKp2SVLlh1fJPyaS7jbT6fP0jyzBgapGtNJISM5hxFrdyXmUx6c3G11X62SwnGNLk4qwlaXOIG5kKwTZYFH2qHpJY+DSfK0zqKuuGp0HX38UzpI5lv/Ih4/YVgsi2gvzrdY+MnxW168nKHxNBHjaI31xJ0q9lJxeZjeyoaKGoykf4p7HUBYCpb+ccnOj6SLHGNPCWbJ5EYvcN17pgewXylSLQA==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
