---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgA+CnZSH+MPs+rq4Gg0B2Tzkhhvm6Yas1ZqkfH5+vutUuZEPBKvcL4EyeqNvkGlmownQgYQicWdj/GC4aaqTuSWk4tkaVurs/gvCBUY5M+PiYvrEdBEb9XoCzNM+J5DANSc8lnqgLceYumSldxrjsSYsrXB6ygDKinU1EyGDzYJ/aBmS71me21cT8PS25FgYjcoT3Jhe/OTabDh0aWqs4nbUPkR30iuJ5gQoSK5LP5Pg+L+xUCJTEGq+rFQJMIeKmxzmln58hw0/i1YKd0pCXmBV992Ig3N+8g3MueoSmYT5LT5KlaFaismHPfopnV1ltTqtfGTOsCa4RpJj83xx2PonEf9dIHppxpBP9BX4lVZCnzUbgggARucP8Jkam+cePFDM7cNcaTKUtBZsUF/RnYeIKz3yB5eV+ZhhhSIJf8Nq2L954t5RRz+WKCZZJ2yxGzIKlZ3wHNzsIkwUVUSjwvhe/Stu0D0cghaJdVNhWJJt0I/6rVMBzjnXwo9fZDG2LZ/njCT3uTx76FygCglqMhKtP/1TZs4+C/ej9sEMOyAoeEWqY5uBXYz6oye2Gq7sTtLojyLiGarOeajTjhjeUYtJX+axDjFGOCxgi4vfpHXKt8p4XtJbrkX7T+i8OZ1uCQifkJi4Yhlrm60Whzv/8FUcmuQ+L6jpvWy8Hdca6sSCFwo8AqvPzByQtFPtmAgZmGte8lQjVAnP4X4sXqhI+RcbBtIfaHhH/9YbHm98puRaz8eiTW3H0QYZeeqnxTuKwf8fZEz5A==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
