apiVersion: v1
kind: ConfigMap
metadata:
  name: health-config
  namespace: homelab
data:
  config.yaml: |
    interval: 15s
    targets:
      - name: traefik
        namespace: traefik
        deployment: traefik
      - name: argocd
        namespace: argocd
        deployment: argocd-server
      - name: homelab-health
        namespace: homelab
        deployment: health
      - name: homelab-action
        namespace: homelab
        deployment: action
      - name: demo-app-1
        namespace: homelab-demo
        deployment: demo-app-1
      - name: demo-app-2
        namespace: homelab-demo
        deployment: demo-app-2
