apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: health
  namespace: homelab
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`hlbe.chammanganti.dev`) && PathPrefix(`/hlh`)
      kind: Rule
      services:
        - name: health
          port: 80
      middlewares:
        - name: health-headers
        - name: health-strip-prefix
  tls:
    secretName: hlbe-tls
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: health-headers
  namespace: homelab
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
    customResponseHeaders:
      Access-Control-Allow-Origin: "https://chammanganti.dev"
      Access-Control-Allow-Methods: "GET,POST,OPTIONS"
      Access-Control-Allow-Headers: "Content-Type"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: health-http
  namespace: homelab
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`hlbe.chammanganti.dev`) && PathPrefix(`/hlh`)
      kind: Rule
      middlewares:
        - name: health-redirect-https
      services:
        - name: health
          port: 80
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: health-redirect-https
  namespace: homelab
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: health-strip-prefix
  namespace: homelab
spec:
  stripPrefix:
    prefixes:
      - /hlh
