{{- if .Values.ingress.enabled }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "home-assistant.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`{{ .Values.ingress.hostname }}`)
      kind: Rule
      services:
        - name: {{ include "home-assistant.fullname" . }}
          port: {{ .Values.service.port }}
      middlewares:
        - name: {{ include "home-assistant.fullname" . }}-ws
  tls:
    secretName: {{ .Values.ingress.tlsSecretName }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "home-assistant.fullname" . }}-ws
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-For: ""
      X-Forwarded-Proto: "https"
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "home-assistant.fullname" . }}-http
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`{{ .Values.ingress.hostname }}`)
      kind: Rule
      middlewares:
        - name: {{ include "home-assistant.fullname" . }}-redirect-https
      services:
        - name: {{ include "home-assistant.fullname" . }}
          port: {{ .Values.service.port }}
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "home-assistant.fullname" . }}-redirect-https
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "home-assistant.labels" . | nindent 4 }}
spec:
  redirectScheme:
    scheme: https
    permanent: true
{{- end }}
